import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  Index,
  ObjectIdColumn
} from 'typeorm'
import { Field, ID, ObjectType } from '@nestjs/graphql'
import { ApiProperty } from '@nestjs/swagger'
import { Collection } from 'fireorm'
import {
  Attribute,
  AutoGeneratedHashKey,
  RangeKey,
  Table,
  VersionAttribute,
  embed
} from 'nestjs-typed-dynamodb'

@ObjectType()
export class Breed {
  @Column({ nullable: true })
  @ApiProperty()
  @Attribute()
  family?: string

  @Column({ nullable: true })
  @ApiProperty()
  @Attribute()
  members?: number
}

// tslint:disable-next-line: max-classes-per-file
@Entity()
@ObjectType()
@Collection('goat')
export class GoatEntity {
  @PrimaryGeneratedColumn('uuid')
  @ObjectIdColumn()
  @ApiProperty()
  @AutoGeneratedHashKey()
  @Field(() => ID)
  id: string

  @Column()
  @Index()
  @ApiProperty()
  @Attribute()
  name: string

  @Column('int')
  @ApiProperty()
  @Attribute()
  age?: number

  @Column(type => Breed)
  @ApiProperty({ type: Breed })
  @Attribute({ memberType: embed(Breed) })
  breed?: Breed
}
