packages:
  - packages/*

catalog:
  eslint: ^9.13.0
  prettier: ^3.3.3
  prisma: ^6.5.0
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
  concurrently: ^9.1.2
  tsx: ^4.19.2
  'ts-jest': '^29.2.6'
  'trpc-to-openapi': '2.3.1'
  '@hatchet-dev/typescript-sdk': '1.6.3'
  'ts-node': '^10.9.2'
  'jest': '^29.7.0'
