import { FormioForm } from '../../../../types/FormioForm'

// The following Forms represent all the possible
// advanced Model relations

export const AdvancedForm: FormioForm[] = ((): FormioForm[] => [
  {
    id: '5ccb6f508fb3ef631896d87d',
    type: 'form',
    tags: [],
    owner: null,
    components: [
      {
        type: 'email',
        persistent: true,
        unique: false,
        protected: false,
        defaultValue: '',
        suffix: '',
        prefix: '',
        placeholder: 'Enter your email address',
        key: 'email',
        lockKey: true,
        label: 'Email',
        inputType: 'email',
        tableView: true,
        input: true
      },
      {
        type: 'password',
        persistent: true,
        protected: true,
        suffix: '',
        prefix: '',
        placeholder: 'Enter your password.',
        key: 'password',
        lockKey: true,
        label: 'Password',
        inputType: 'password',
        tableView: false,
        input: true
      },
      {
        type: 'button',
        theme: 'primary',
        disableOnInvalid: true,
        action: 'submit',
        block: false,
        rightIcon: '',
        leftIcon: '',
        size: 'md',
        key: 'submit',
        tableView: false,
        label: 'Submit',
        input: true
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'User Login',
    name: 'userLogin',
    path: 'user/login',
    access: [{ roles: ['5ccb6f508fb3efe5f396d87a'], type: 'read_all' }],
    submissionAccess: [
      { roles: ['5ccb6f508fb3efe5f396d87a'], type: 'create_own' }
    ],
    machineName: 'suopywgtyuabhru:userLogin',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-05-02T22:29:36.663Z',
    modified: '2019-05-02T22:29:36.665Z'
  },
  {
    id: '5d70d27477462637b737d03e',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'Name',
        key: 'name',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        spellcheck: true,
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          pattern: '',
          custom: '',
          customPrivate: false
        },
        conditional: { show: '', when: null, eq: '' },
        type: 'textfield',
        labelPosition: 'top',
        inputFormat: 'plain',
        tags: [],
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Customer_1N',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'customer1N',
    path: 'customer1n',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:16:36.064Z',
    modified: '2019-09-05T09:16:51.376Z',
    machineName: 'suopywgtyuabhru:customer1N'
  },
  {
    id: '5d70d29306588ea15a6b13b2',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'Date',
        key: 'date',
        placeholder: '',
        format: 'yyyy-MM-dd hh:mm a',
        enableDate: true,
        enableTime: true,
        defaultDate: '',
        datepickerMode: 'day',
        datePicker: {
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
          minDate: null,
          maxDate: null,
          datepickerMode: 'day'
        },
        timePicker: {
          hourStep: 1,
          minuteStep: 1,
          showMeridian: true,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true
        },
        protected: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false, custom: '' },
        type: 'datetime',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'costumer',
        key: 'costumer',
        placeholder: '',
        data: {
          values: [{ value: '', label: '' }],
          json: '',
          url: '',
          resource: '5d70d27477462637b737d03e',
          custom: '',
          project: 'suopywgtyuabhru'
        },
        dataSrc: 'resource',
        valueProperty: 'id',
        defaultValue: '',
        refreshOn: '',
        filter: '',
        authenticate: false,
        template: '<span>{{ item.id }}</span>',
        multiple: false,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false },
        type: 'select',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {},
        searchField: 'id__regex'
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Order_1N',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'order1N',
    path: 'order1n',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:17:07.915Z',
    modified: '2019-09-05T09:18:22.924Z',
    machineName: 'suopywgtyuabhru:order1N'
  },
  {
    id: '5d70d33806588e3c9a6b13cf',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'Name',
        key: 'name',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        spellcheck: true,
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          pattern: '',
          custom: '',
          customPrivate: false
        },
        conditional: { show: '', when: null, eq: '' },
        type: 'textfield',
        labelPosition: 'top',
        inputFormat: 'plain',
        tags: [],
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'Orders',
        key: 'orders',
        placeholder: '',
        data: {
          values: [{ value: '', label: '' }],
          json: '',
          url: '',
          resource: '5d70d3998e9aff0a31f3c4fe',
          custom: '',
          project: 'suopywgtyuabhru'
        },
        dataSrc: 'resource',
        valueProperty: 'id',
        defaultValue: '',
        refreshOn: '',
        filter: '',
        authenticate: false,
        template: '<span>{{ item.id }}</span>',
        multiple: true,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false },
        type: 'select',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {},
        searchField: 'id__regex',
        isNew: false
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Customer_1N_Embedded',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'customer1NEmbedded',
    path: 'customer1nembedded',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:19:52.306Z',
    modified: '2019-09-05T09:27:10.952Z',
    machineName: 'suopywgtyuabhru:customer1NEmbedded'
  },
  {
    id: '5d70d3998e9aff0a31f3c4fe',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'Date',
        key: 'date',
        placeholder: '',
        format: 'yyyy-MM-dd hh:mm a',
        enableDate: true,
        enableTime: true,
        defaultDate: '',
        datepickerMode: 'day',
        datePicker: {
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
          minDate: null,
          maxDate: null,
          datepickerMode: 'day'
        },
        timePicker: {
          hourStep: 1,
          minuteStep: 1,
          showMeridian: true,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true
        },
        protected: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false, custom: '' },
        type: 'datetime',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Order_1N_Embedded',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'order1NEmbedded',
    path: 'order1nembedded',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:21:29.824Z',
    modified: '2019-09-05T09:21:29.827Z',
    machineName: 'suopywgtyuabhru:order1NEmbedded'
  },
  {
    id: '5d70d54006588eada86b142a',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'Name',
        key: 'name',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        spellcheck: true,
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          pattern: '',
          custom: '',
          customPrivate: false
        },
        conditional: { show: '', when: null, eq: '' },
        type: 'textfield',
        labelPosition: 'top',
        inputFormat: 'plain',
        tags: [],
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        tree: true,
        components: [
          {
            autofocus: false,
            input: true,
            tableView: true,
            label: 'order',
            key: 'dgOrder',
            placeholder: '',
            data: {
              values: [{ value: '', label: '' }],
              json: '',
              url: '',
              resource: '5d70d3998e9aff0a31f3c4fe',
              custom: '',
              project: 'suopywgtyuabhru'
            },
            dataSrc: 'resource',
            valueProperty: 'id',
            defaultValue: '',
            refreshOn: '',
            filter: '',
            authenticate: false,
            template: '<span>{{ item.id }}</span>',
            multiple: false,
            protected: false,
            unique: false,
            persistent: true,
            hidden: false,
            clearOnHide: true,
            validate: { required: false },
            type: 'select',
            inDataGrid: true,
            labelPosition: 'top',
            tags: [],
            conditional: { show: '', when: null, eq: '' },
            properties: {},
            searchField: 'id__regex'
          }
        ],
        tableView: true,
        label: 'DG',
        key: 'dg',
        protected: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        type: 'datagrid',
        addAnotherPosition: 'bottom',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Customer_1N_Embedded_DG',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'customer1NEmbeddedDg',
    path: 'customer1nembeddeddg',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:28:32.105Z',
    modified: '2019-09-05T09:33:04.736Z',
    machineName: 'suopywgtyuabhru:customer1NEmbeddedDg'
  },
  {
    id: '5d70d8bb43315d71a05c1347',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'name',
        key: 'name',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        spellcheck: true,
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          pattern: '',
          custom: '',
          customPrivate: false
        },
        conditional: { show: '', when: null, eq: '' },
        type: 'textfield',
        labelPosition: 'top',
        inputFormat: 'plain',
        tags: [],
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Users_NM',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'usersNm',
    path: 'usersnm',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:43:23.259Z',
    modified: '2019-09-05T09:43:23.264Z',
    machineName: 'suopywgtyuabhru:usersNm'
  },
  {
    id: '5d70d8d63f1bee14d06355f6',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'Name',
        key: 'name',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        spellcheck: true,
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          pattern: '',
          custom: '',
          customPrivate: false
        },
        conditional: { show: '', when: null, eq: '' },
        type: 'textfield',
        labelPosition: 'top',
        inputFormat: 'plain',
        tags: [],
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Products_NM',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'productsNm',
    path: 'productsnm',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:43:50.801Z',
    modified: '2019-09-05T09:43:50.804Z',
    machineName: 'suopywgtyuabhru:productsNm'
  },
  {
    id: '5d70d8ec774626bd5337d15c',
    type: 'resource',
    tags: [],
    owner: '573cc203e35b990100f16c0a',
    components: [
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'user',
        key: 'user',
        placeholder: '',
        data: {
          values: [{ value: '', label: '' }],
          json: '',
          url: '',
          resource: '5d70d8bb43315d71a05c1347',
          custom: '',
          project: 'suopywgtyuabhru'
        },
        dataSrc: 'resource',
        valueProperty: 'id',
        defaultValue: '',
        refreshOn: '',
        filter: '',
        authenticate: false,
        template: '<span>{{ item.id }}</span>',
        multiple: false,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false },
        type: 'select',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {},
        searchField: 'id__regex'
      },
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'product',
        key: 'product',
        placeholder: '',
        data: {
          values: [{ value: '', label: '' }],
          json: '',
          url: '',
          resource: '5d70d8d63f1bee14d06355f6',
          custom: '',
          project: 'suopywgtyuabhru'
        },
        dataSrc: 'resource',
        valueProperty: 'id',
        defaultValue: '',
        refreshOn: '',
        filter: '',
        authenticate: false,
        template: '<span>{{ item.id }}</span>',
        multiple: false,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false },
        type: 'select',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {},
        searchField: 'id__regex'
      },
      {
        autofocus: false,
        input: true,
        tableView: true,
        inputType: 'number',
        label: 'price',
        key: 'price',
        placeholder: '',
        prefix: '',
        suffix: '',
        defaultValue: '',
        protected: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: {
          required: false,
          min: '',
          max: '',
          step: 'any',
          integer: '',
          multiple: '',
          custom: ''
        },
        type: 'number',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        tableView: true,
        label: 'date',
        key: 'date',
        placeholder: '',
        format: 'yyyy-MM-dd hh:mm a',
        enableDate: true,
        enableTime: true,
        defaultDate: '',
        datepickerMode: 'day',
        datePicker: {
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
          minDate: null,
          maxDate: null,
          datepickerMode: 'day'
        },
        timePicker: {
          hourStep: 1,
          minuteStep: 1,
          showMeridian: true,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true
        },
        protected: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        validate: { required: false, custom: '' },
        type: 'datetime',
        labelPosition: 'top',
        tags: [],
        conditional: { show: '', when: null, eq: '' },
        properties: {}
      },
      {
        autofocus: false,
        input: true,
        label: 'Submit',
        tableView: false,
        key: 'submit',
        size: 'md',
        leftIcon: '',
        rightIcon: '',
        block: false,
        action: 'submit',
        disableOnInvalid: false,
        theme: 'primary',
        type: 'button'
      }
    ],
    revisions: '',
    _vid: 0,
    title: 'Orders_NM',
    display: 'form',
    access: [
      {
        roles: [
          '5ccb6f508fb3ef6c4f96d878',
          '5ccb6f508fb3ef48fb96d879',
          '5ccb6f508fb3efe5f396d87a'
        ],
        type: 'read_all'
      }
    ],
    submissionAccess: [],
    settings: {},
    properties: {},
    name: 'ordersNm',
    path: 'ordersnm',
    project: '5ccb6f508fb3ef72b796d877',
    created: '2019-09-05T09:44:12.166Z',
    modified: '2019-09-05T09:47:27.037Z',
    machineName: 'suopywgtyuabhru:ordersNm'
  }
])()
