// Delphi self-hosting loop — run with: pnpm example:self-improve
// (Requires Docker. Spins a throwaway Postgres unless DATABASE_URL is set.)
//
// Demonstrates the full governance loop running ON THIS REPO:
//   Observe   — scan the delphi-* packages (self-knowledge)
//   Review    — perspective review of the "self-document & assess" decision
//   Execute   — compile each Action into a real delphi-core workflow run
//   Measure   — record an Outcome per run back to the Brain
//   Document  — the workflows WRITE generated docs + assessments to disk
//
// i.e. Delphi self-assesses, self-documents, and records what it learned.
import { execFileSync } from 'node:child_process'
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import pg from 'pg'
import {
  createDbClient,
  CREATE_TABLES_SQL,
  createEngine,
  FunctionStep,
  runMigrations,
  type StepPayload,
  Workflow,
  WorkflowStepTask,
} from '@goatlab/delphi-core'
import {
  CompileRegistry,
  createGovernance,
  fromEngine,
  type Governance,
  heuristicPerspectiveEvaluator,
  InMemoryBrainClient,
  STANDARD_PERSPECTIVES,
} from '../src/index.js'
import type { Action, Decision } from '../src/index.js'
import { getPostgres } from './pg.js'

const TENANT = 'delphi'
// Portable __dirname (works under tsx's CJS transform and native ESM).
const HERE = dirname(fileURLToPath(import.meta.url))
const PACKAGES_DIR = join(HERE, '..', '..')
const OUT_DIR = join(HERE, 'output')

// ── Self-knowledge helpers ──────────────────────────────────────────
function countFiles(dir: string, ext: string): number {
  let n = 0
  const walk = (d: string) => {
    let entries: string[]
    try {
      entries = readdirSync(d)
    } catch {
      return
    }
    for (const e of entries) {
      if (e === 'node_modules' || e === 'dist' || e.startsWith('.')) continue
      const p = join(d, e)
      const s = statSync(p)
      if (s.isDirectory()) walk(p)
      else if (e.endsWith(ext)) n++
    }
  }
  walk(dir)
  return n
}

function readPkg(dir: string): { name?: string; version?: string; description?: string } {
  try {
    return JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  } catch {
    return {}
  }
}

function exists(p: string): boolean {
  try {
    statSync(p)
    return true
  } catch {
    return false
  }
}

// ── Workflows (the execution plane does real work on this repo) ──────

interface PkgInput {
  packageDir: string
  name: string
  [k: string]: unknown
}

/** Reads a package and writes a generated narrative doc. Self-documentation. */
class DocumentPackageStep extends FunctionStep<PkgInput, { docPath: string; tsFiles: number }> {
  stepName = 'document_package' as const
  async handle(input: PkgInput) {
    const pkg = readPkg(input.packageDir)
    const tsFiles = countFiles(join(input.packageDir, 'src'), '.ts')
    const readme = exists(join(input.packageDir, 'README.md'))
      ? readFileSync(join(input.packageDir, 'README.md'), 'utf8').split('\n').slice(0, 3).join('\n')
      : '_(no README)_'
    const doc = [
      `# ${pkg.name ?? input.name}`,
      '',
      `> Auto-generated by the Delphi self-documentation loop.`,
      '',
      `- **Version:** ${pkg.version ?? 'n/a'}`,
      `- **Description:** ${pkg.description ?? 'n/a'}`,
      `- **TypeScript source files:** ${tsFiles}`,
      '',
      '## README excerpt',
      '',
      readme,
      '',
    ].join('\n')
    mkdirSync(join(OUT_DIR, 'narratives'), { recursive: true })
    const docPath = join(OUT_DIR, 'narratives', `${input.name}.md`)
    writeFileSync(docPath, doc)
    return { output: { docPath, tsFiles } }
  }
}

class DocumentPackageWorkflow extends Workflow<PkgInput> {
  workflowName = 'documentPackage' as const
  steps = [new DocumentPackageStep()] as const
}

/** Scores a package's health and writes an assessment. Self-assessment. */
class AssessPackageStep extends FunctionStep<PkgInput, { score: number; gaps: string[] }> {
  stepName = 'assess_package' as const
  async handle(input: PkgInput) {
    const checks: Array<[string, boolean]> = [
      ['README.md', exists(join(input.packageDir, 'README.md'))],
      ['package.json', exists(join(input.packageDir, 'package.json'))],
      ['src/', exists(join(input.packageDir, 'src'))],
      ['tests', countFiles(input.packageDir, '.spec.ts') > 0],
      ['tsconfig.json', exists(join(input.packageDir, 'tsconfig.json'))],
    ]
    const passed = checks.filter(([, ok]) => ok).length
    const score = Math.round((passed / checks.length) * 100)
    const gaps = checks.filter(([, ok]) => !ok).map(([n]) => n)
    const doc = [
      `# Assessment: ${input.name}`,
      '',
      `> Auto-generated by the Delphi self-assessment loop.`,
      '',
      `**Health score: ${score}/100**`,
      '',
      ...checks.map(([n, ok]) => `- [${ok ? 'x' : ' '}] ${n}`),
      '',
    ].join('\n')
    mkdirSync(join(OUT_DIR, 'assessments'), { recursive: true })
    writeFileSync(join(OUT_DIR, 'assessments', `${input.name}.md`), doc)
    return { output: { score, gaps } }
  }
}

class AssessPackageWorkflow extends Workflow<PkgInput> {
  workflowName = 'assessPackage' as const
  steps = [new AssessPackageStep()] as const
}

// ── Main loop ───────────────────────────────────────────────────────

async function main() {
  console.log('\n🧠  Delphi self-hosting loop — running on this repo\n')

  // OBSERVE — discover the delphi-* packages (the company looking at itself).
  const pkgDirs = readdirSync(PACKAGES_DIR)
    .filter(d => d.startsWith('delphi-'))
    .map(d => join(PACKAGES_DIR, d))
    .filter(d => exists(join(d, 'package.json')))
  console.log(`  Observed ${pkgDirs.length} delphi packages: ${pkgDirs.map(d => basename(d)).join(', ')}\n`)

  // Seed the Brain (judgment plane): one decision + a document/assess action per package.
  const decision: Decision = {
    name: 'self-document-and-assess-delphi',
    kind: 'decision',
    description: 'Continuously document and assess every Delphi package so the system understands itself.',
    status: 'approved',
    choice: 'Generate a narrative doc and a health assessment for each package.',
  }
  const actions: Action[] = pkgDirs.flatMap(dir => {
    const name = basename(dir)
    return [
      { name: `document-${name}`, kind: 'action', description: `Document ${name}`, type: 'document', status: 'proposed', target: dir },
      { name: `assess-${name}`, kind: 'action', description: `Assess ${name}`, type: 'assess', status: 'proposed', target: dir },
    ]
  })
  const brain = new InMemoryBrainClient({ actions, decisions: [decision] })

  // Bring up the execution plane (delphi-core on Postgres).
  const { connectionString, stop: stopPg } = await getPostgres()
  const pgPool = new pg.Pool({ connectionString, max: 8 })
  const db = createDbClient(pgPool)
  console.log('  Creating schema ...')
  for (const stmt of CREATE_TABLES_SQL.split(';').map(s => s.trim()).filter(Boolean)) {
    await pgPool.query(stmt)
  }
  await runMigrations(db)

  let governance: Governance
  const engine = createEngine({
    workflows: [new DocumentPackageWorkflow(), new AssessPackageWorkflow()] as const,
    database: pgPool,
    tenantId: TENANT,
    dispatch: { pollingIntervalMs: 50 },
    onEngineEvent: evt => governance?.onEngineEvent(evt),
  })

  // Start a worker so enqueued steps actually run. In Postgres-only mode the
  // PgConnector claims steps from workflow_steps and routes them all to the
  // first registered handler — so a single step handler is exactly right (the
  // IngestWorker/ingest queue is only for the BullMQ buffered path).
  const connector = engine.connector
  const stepTask = new WorkflowStepTask(engine)
  stepTask.setConnector(connector)
  const stepHandle = (data: unknown) => stepTask.handle(data as StepPayload)
  const workerHandle = await connector.listen({
    tasks: [{ taskName: 'workflow_step', handle: stepHandle, concurrency: 8 }],
    defaultConcurrency: 8,
  })

  // Wire governance: review (heuristic, offline) + compile registry + measure.
  const registry = new CompileRegistry()
    .register('document', { workflowName: 'documentPackage', mapInput: a => ({ packageDir: a.target as string, name: basename(a.target as string) }) })
    .register('assess', { workflowName: 'assessPackage', mapInput: a => ({ packageDir: a.target as string, name: basename(a.target as string) }) })

  governance = createGovernance({
    brain,
    starter: fromEngine(engine as unknown as Record<string, unknown>),
    registry,
    review: { evaluator: heuristicPerspectiveEvaluator() },
  })

  // REVIEW — perspectives weigh in on the decision (tradeoffs, not consensus).
  console.log('  ── Review (perspectives) ──')
  const review = await governance.reviewDecision(decision, STANDARD_PERSPECTIVES)
  for (const v of review.matrix.verdicts) {
    console.log(`    ${v.perspective.padEnd(12)} ${v.assessment}${v.concerns[0] ? `  (${v.concerns[0]})` : ''}`)
  }
  console.log(`    → outcome: ${review.outcome} (score ${review.score.toFixed(2)})\n`)
  if (review.outcome === 'rejected') {
    console.log('  Decision rejected by review — stopping.')
    teardown()
  }

  // EXECUTE — compile each approved action into an exactly-once workflow run.
  console.log('  ── Execute (compile decisions → workflows) ──')
  const results = await governance.tick()
  const executing = results.filter(r => r.status === 'executing')
  for (const r of results) {
    console.log(`    ${r.item.padEnd(34)} ${r.status}${r.runId ? `  run=${r.runId.slice(0, 8)}` : ''}`)
  }
  console.log(`    started ${executing.length} runs\n`)

  // MEASURE — wait for outcomes to land (run.completed → recorded back to Brain).
  console.log('  ── Measure (await outcomes) ──')
  const deadline = Date.now() + 60_000
  while (brain.outcomes.length < executing.length && Date.now() < deadline) {
    await new Promise(r => setTimeout(r, 200))
  }
  const completed = brain.outcomes.filter(o => o.status === 'COMPLETED').length
  console.log(`    ${brain.outcomes.length}/${executing.length} outcomes recorded (${completed} COMPLETED)\n`)

  // LEARN — write a loop record (self-evolution trace).
  mkdirSync(OUT_DIR, { recursive: true })
  const stamp = new Date().toISOString()
  const log = [
    `## [${stamp}] self-document-and-assess-delphi`,
    `- review: ${review.outcome} (score ${review.score.toFixed(2)})`,
    `- actions executed: ${executing.length}`,
    `- outcomes: ${brain.outcomes.length} (${completed} completed)`,
    ...brain.outcomes.map(o => `  - ${o.itemName}: ${o.status}`),
    '',
  ].join('\n')
  writeFileSync(join(OUT_DIR, 'log.md'), log)
  console.log(`  📝 wrote generated docs + assessments + log to:\n     ${OUT_DIR}\n`)

  // CONNECT BRAIN — ingest the self-generated docs into the Delphi Brain so
  // institutional memory grows and becomes queryable. This closes the loop:
  // Delphi documented itself → the Brain now knows about its own packages.
  console.log('  ── Connect Brain (index self-docs into institutional memory) ──')
  try {
    const brainBin = join(HERE, '..', '..', 'delphi-brain', 'cli', 'brain')
    if (!exists(brainBin)) {
      throw new Error('brain binary not built — run: cd packages/delphi-brain && make build')
    }
    writeFileSync(
      join(OUT_DIR, 'brain.config.json'),
      JSON.stringify(
        { org: { name: 'Goat Fluent / Delphi', description: 'The Delphi agent OS monorepo, documenting itself.' } },
        null,
        2,
      ),
    )
    const env = {
      ...process.env,
      BRAIN_ROOT: OUT_DIR,
      BRAIN_DB: join(OUT_DIR, 'brain.db'),
      BRAIN_SCHEMA_DIR: join(HERE, '..', '..', 'delphi-brain', 'schema'),
    }
    const brain = (args: string[]) => execFileSync(brainBin, args, { env, encoding: 'utf8' }).trim()
    brain(['index', '--root', OUT_DIR])
    const docCount = brain(['query', 'SELECT count(*) AS documents FROM documents']).replace(/\s+/g, ' ')
    const sample = brain(['query', "SELECT path FROM documents WHERE path LIKE '%assessments%' LIMIT 3"])
    console.log(`    Brain indexed self-docs → ${docCount}`)
    console.log(`    now queryable, e.g. assessments:\n${sample.split('\n').map(l => `      ${l}`).join('\n')}`)
    console.log('    🧠 institutional memory updated — the Brain knows about its own packages.\n')
  } catch (err) {
    console.log(`    (skipped Brain indexing: ${(err as Error).message})\n`)
  }

  console.log('  ✅ self-hosting loop complete: reviewed → executed → documented → measured → learned → remembered.\n')

  teardown()

  function teardown(): never {
    // The engine + connector keep internal poll loops / timers running. Rather
    // than chase every one, stop the worker, drop the throwaway container, and
    // exit — the OS reclaims the pool + sockets immediately.
    void workerHandle.stop().catch(() => {})
    stopPg()
    process.exit(0)
  }
}

main().catch(err => {
  console.error('\n❌ self-improve failed:', err)
  process.exit(1)
})
