// npx vitest run src/__tests__/engine/lifecycle.spec.ts
//
// Database schema — no decorators, no classes, no reflection.
// Works with Postgres AND SQLite.
//

/**
 * Marks a column as auto-generated by the database (e.g. DEFAULT CURRENT_TIMESTAMP).
 * At the TS level, the resolved type is just T — the wrapper is documentation-only.
 */
type Generated<T> = T

// ── Workflow Runs ──────────────────────────────────────────────────

export interface WorkflowRunTable {
  id: string
  tenantId: string
  workflowName: string
  workflowVersion: string
  status: string
  definitionSnapshot: string | null // JSON: frozen workflow definition at start time
  triggerInput: string | null
  output: string | null
  error: string | null
  idempotencyKey: string | null
  /** Trace ID for cross-workflow lineage */
  traceId: string | null
  /** Parent workflow run ID (for child workflows) */
  parentRunId: string | null
  /** Origin event ID that triggered this workflow */
  originEventId: string | null
  /** Budget guardrails config (JSON) */
  budget: string | null
  /** Accumulated budget usage (JSON) */
  budgetUsed: string | null
  /** DBOS-parity: workflow-level deadline (epoch ms) for timeout enforcement */
  deadlineEpochMs: string | number | null
  /** DBOS-parity: workflow-level timeout in ms */
  timeoutMs: string | number | null
  /** DBOS-parity: run ID this workflow was forked from */
  forkedFromRunId: string | null
  /** DBOS-parity: application version for version-aware dispatch */
  applicationVersion: string | null
  /** DBOS-parity: epoch ms until which a DELAYED workflow should wait */
  delayUntilEpochMs: string | number | null
  startedAt: Date | string | null
  completedAt: Date | string | null
  createdAt: Generated<Date | string>
  updatedAt: Generated<Date | string>
}

export type WorkflowRun = WorkflowRunTable
export type NewWorkflowRun = Partial<WorkflowRunTable>
export type WorkflowRunUpdate = Partial<WorkflowRunTable>

// ── Workflow Steps ─────────────────────────────────────────────────

export interface WorkflowStepTable {
  id: string
  workflowRunId: string
  tenantId: string
  stepName: string
  status: string
  executorType: string
  executorConfig: string | null
  dependsOn: string | null // JSON array of step names
  input: string | null
  output: string | null
  error: string | null
  attempt: number
  maxRetries: number
  startedAt: Date | string | null
  completedAt: Date | string | null
  scheduledAt: Date | string | null
  lastHeartbeatAt: Date | string | null
  lastHeartbeatData: string | null
  heartbeatTimeoutMs: number | null
  humanPrompt: string | null
  humanResponse: string | null
  humanRespondedBy: string | null
  humanRespondedAt: Date | string | null
  /** nextStep loop iteration tracking */
  iterationCount: number | null
  maxIterations: number | null
  /** Cost tracking: total tokens used by this step */
  tokensUsed: number | null
  /** Cost tracking: estimated cost in USD (e.g., 0.0023) */
  costUsd: string | null
  /** Cost tracking: model used (e.g., 'gpt-4o', 'claude-sonnet-4-20250514') */
  modelUsed: string | null
  /** Worker identity: which machine/process executed this step */
  executedBy: string | null
  /**
   * Labels a worker MUST advertise to be eligible to run this step.
   * Serialized JSON array (e.g. `["sdlc","claude-max"]`). Used by the
   * WorkerBroker's AND-match scheduling. When null / empty, any
   * worker subscribed to this step's queue is eligible. Mirrors
   * `StepDefinition.requiresLabels`.
   */
  requiresLabels: string | null
  /** Epoch ms until which a retrying step should wait before being re-claimed */
  retryAfterMs: string | number | null
  /** DBOS-parity: epoch ms deadline for durable sleep */
  deadlineEpochMs: string | number | null
  createdAt: Generated<Date | string>
  updatedAt: Generated<Date | string>
}

export type WorkflowStep = WorkflowStepTable
export type NewWorkflowStep = Partial<WorkflowStepTable>
export type WorkflowStepUpdate = Partial<WorkflowStepTable>

// ── Workflow Step Logs ─────────────────────────────────────────────

export type StepLogEvent =
  | 'queued'
  | 'started'
  | 'completed'
  | 'failed'
  | 'retried'
  | 'skipped'
  | 'human_requested'
  | 'human_responded'
  | 'heartbeat'
  | 'cancelled'
  | 'rollback_started'
  | 'rollback_completed'
  | 'rollback_failed'

export interface WorkflowStepLogTable {
  id: string
  stepId: string
  /** FK to workflow_runs for CASCADE deletion (DBOS-parity: log retention) */
  workflowRunId: string | null
  tenantId: string
  event: string
  data: string | null
  createdAt: Generated<Date | string>
}

export type WorkflowStepLog = WorkflowStepLogTable
export type NewWorkflowStepLog = Partial<WorkflowStepLogTable>

// ── Workflow Signals ───────────────────────────────────────────────

export interface WorkflowSignalTable {
  id: string
  workflowRunId: string
  tenantId: string
  signalName: string
  data: string
  processedAt: Date | string | null
  createdAt: Generated<Date | string>
}

export type WorkflowSignal = WorkflowSignalTable
export type NewWorkflowSignal = Partial<WorkflowSignalTable>

// ── External Actions ───────────────────────────────────────────────
// The consistency layer for ALL side effects that touch the real world.
// Every external API call (create PR, create issue, send email, deploy)
// MUST go through this table. This guarantees exactly-once execution
// even across retries and worker crashes.

export type ExternalActionStatus =
  | 'pending'
  | 'completing'
  | 'completed'
  | 'failed'

export interface ExternalActionTable {
  id: string
  workflowRunId: string
  stepName: string
  attempt: number
  tenantId: string

  provider: string // 'github' | 'linear' | 'slack' | etc
  actionType: string // 'create_pr' | 'create_issue' | 'comment' | etc
  idempotencyKey: string // unique per action, e.g. '{runId}:{stepName}:{actionType}'

  status: string // 'pending' | 'completed' | 'failed'
  externalId: string | null // The ID returned by the external system (PR id, issue id)

  request: string | null // JSON: what we sent
  response: string | null // JSON: what we got back
  error: string | null // Error message if failed

  /** Trace ID for cross-workflow lineage */
  traceId: string | null

  createdAt: Generated<Date | string>
  completedAt: Date | string | null
}

export type ExternalAction = ExternalActionTable
export type NewExternalAction = Partial<ExternalActionTable>
export type ExternalActionUpdate = Partial<ExternalActionTable>

// ── Workflow Events ───────────────────────────────────────────────

export interface WorkflowEventTable {
  id: string
  tenantId: string
  eventType: string
  source: string
  payload: string | null
  idempotencyKey: string | null
  /** Entity key for ordering (e.g. 'github:pr:123') */
  entityKey: string | null
  /** Sequence number within entity — higher = newer */
  sequenceNumber: number | null
  /** Trace ID for cross-workflow lineage */
  traceId: string | null
  status: string // 'pending' | 'processed' | 'failed' | 'dead_letter' | 'skipped_stale'
  error: string | null
  processedAt: Date | string | null
  createdAt: Generated<Date | string>
}

export type WorkflowEvent = WorkflowEventTable
export type NewWorkflowEvent = Partial<WorkflowEventTable>
export type WorkflowEventUpdate = Partial<WorkflowEventTable>

// ── Workflow Event Subscriptions ──────────────────────────────────

export interface WorkflowEventSubscriptionTable {
  id: string
  tenantId: string
  eventType: string
  workflowName: string
  filterExpression: string | null
  active: boolean
  createdAt: Generated<Date | string>
}

export type WorkflowEventSubscription = WorkflowEventSubscriptionTable
export type NewWorkflowEventSubscription =
  Partial<WorkflowEventSubscriptionTable>

// ── Worker Nodes ──────────────────────────────────────────────────

export interface WorkerNodeTable {
  id: string
  tenantId: string | null
  accountId: string | null
  name: string
  hostname: string | null
  capabilities: string | null
  secretHash: string | null
  status: string
  lastHeartbeatAt: Date | string | null
  registeredAt: Generated<Date | string>
  createdAt: Generated<Date | string>
}

export type WorkerNodeRow = WorkerNodeTable
export type NewWorkerNode = Partial<WorkerNodeTable>
export type WorkerNodeUpdate = Partial<WorkerNodeTable>

// ── Workflow Definitions ──────────────────────────────────────────

export interface WorkflowDefinitionTable {
  id: string
  tenantId: string
  name: string
  version: string
  definition: string
  createdBy: string | null
  createdAt: Generated<Date | string>
  updatedAt: Generated<Date | string>
}

export type WorkflowDefinitionRow = WorkflowDefinitionTable
export type NewWorkflowDefinition = Partial<WorkflowDefinitionTable>
export type WorkflowDefinitionUpdate = Partial<WorkflowDefinitionTable>

// ── Workflow Tasks ────────────────────────────────────────────────

export type WorkflowTaskStatus = 'pending' | 'running' | 'completed' | 'failed'

export interface WorkflowTaskTable {
  id: string
  workflowRunId: string
  stepName: string
  status: string
  payload: string | null
  result: string | null
  error: string | null
  attempt: number
  maxRetries: number
  priority: number | null
  /** DBOS-parity: partition key for queue partitioning */
  queuePartitionKey: string | null
  createdAt: Generated<Date | string>
  updatedAt: Generated<Date | string>
}

export type WorkflowTask = WorkflowTaskTable
export type NewWorkflowTask = Partial<WorkflowTaskTable>
export type WorkflowTaskUpdate = Partial<WorkflowTaskTable>

// ── Workflow Schedules ────────────────────────────────────────────

export interface WorkflowScheduleTable {
  id: string
  tenantId: string
  workflowName: string
  cronExpression: string
  /** IANA timezone identifier for cron evaluation (e.g., 'America/New_York'). Default: 'UTC'. */
  timezone: string
  /** Fire immediately on first sync/startup, then follow the cron pattern. */
  runOnInit: boolean
  /** Default input for each scheduled run (JSON) */
  input: string | null
  /** Next run time as epoch milliseconds (avoids timezone issues) */
  nextRunAtEpochMs: number | string
  /** Last run time as epoch milliseconds */
  lastRunAtEpochMs: number | string | null
  active: boolean
  createdAt: Generated<Date | string>
}

export type WorkflowSchedule = WorkflowScheduleTable
export type NewWorkflowSchedule = Partial<WorkflowScheduleTable>
export type WorkflowScheduleUpdate = Partial<WorkflowScheduleTable>

// ── Database Schema ────────────────────────────────────────────────

// ── Agent Tokens ──────────────────────────────────────────────────

export interface AgentTokenTable {
  id: string
  tenantId: string
  token: string
  used: boolean
  usedBy: string | null
  expiresAt: Date | string | null
  createdAt: Generated<Date | string>
}

export type AgentToken = AgentTokenTable
export type NewAgentToken = Partial<AgentTokenTable>

// ── Workflow Streams ──────────────────────────────────────────────

export interface WorkflowStreamTable {
  id: string
  workflowRunId: string
  key: string
  offset: number
  value: string
  createdAt: Generated<Date | string>
}

export type WorkflowStream = WorkflowStreamTable
export type NewWorkflowStream = Partial<WorkflowStreamTable>

// ── Database Schema ────────────────────────────────────────────────

export interface Database {
  workflow_runs: WorkflowRunTable
  workflow_steps: WorkflowStepTable
  workflow_step_logs: WorkflowStepLogTable
  workflow_signals: WorkflowSignalTable
  external_actions: ExternalActionTable
  workflow_events: WorkflowEventTable
  workflow_event_subscriptions: WorkflowEventSubscriptionTable
  worker_nodes: WorkerNodeTable
  workflow_definitions: WorkflowDefinitionTable
  workflow_tasks: WorkflowTaskTable
  workflow_schedules: WorkflowScheduleTable
  agent_tokens: AgentTokenTable
  workflow_streams: WorkflowStreamTable
}

// ── JSON Helpers ───────────────────────────────────────────────────

export function toJson(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null
  }
  return JSON.stringify(value)
}

export function fromJson<T = Record<string, unknown>>(
  value: string | null | undefined,
): T | null {
  if (value === null || value === undefined) {
    return null
  }
  try {
    return JSON.parse(value) as T
  } catch {
    return null
  }
}

// ── Table Creation SQL ─────────────────────────────────────────────

export const CREATE_TABLES_SQL = `
CREATE TABLE IF NOT EXISTS workflow_runs (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  "workflowName" VARCHAR(255) NOT NULL,
  "workflowVersion" VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  "definitionSnapshot" TEXT,
  "triggerInput" TEXT,
  output TEXT,
  error TEXT,
  "idempotencyKey" VARCHAR(255),
  "traceId" VARCHAR(36),
  "parentRunId" VARCHAR(36),
  "originEventId" VARCHAR(36),
  budget TEXT,
  "budgetUsed" TEXT,
  "deadlineEpochMs" BIGINT,
  "timeoutMs" BIGINT,
  "forkedFromRunId" VARCHAR(36),
  "applicationVersion" VARCHAR(100),
  "delayUntilEpochMs" BIGINT,
  "startedAt" TIMESTAMPTZ,
  "completedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Tenant-scoped idempotency: two tenants can legitimately use the
  -- same idempotencyKey without colliding. Within a tenant, the
  -- constraint + pre-SELECT dedupe in startBatchCopy guarantee at
  -- most one run per key.
  UNIQUE("tenantId", "idempotencyKey")
);

CREATE TABLE IF NOT EXISTS workflow_steps (
  id VARCHAR(36) PRIMARY KEY,
  "workflowRunId" VARCHAR(36) NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  "tenantId" VARCHAR(255) NOT NULL,
  "stepName" VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  "executorType" VARCHAR(100) NOT NULL,
  "executorConfig" TEXT,
  "dependsOn" TEXT,
  input TEXT,
  output TEXT,
  error TEXT,
  attempt INTEGER NOT NULL DEFAULT 0,
  "maxRetries" INTEGER NOT NULL DEFAULT 3,
  "startedAt" TIMESTAMPTZ,
  "completedAt" TIMESTAMPTZ,
  "scheduledAt" TIMESTAMPTZ,
  "lastHeartbeatAt" TIMESTAMPTZ,
  "lastHeartbeatData" TEXT,
  "heartbeatTimeoutMs" INTEGER,
  "humanPrompt" TEXT,
  "humanResponse" TEXT,
  "humanRespondedBy" VARCHAR(255),
  "humanRespondedAt" TIMESTAMPTZ,
  "iterationCount" INTEGER DEFAULT 0,
  "maxIterations" INTEGER,
  "tokensUsed" INTEGER,
  "costUsd" VARCHAR(20),
  "modelUsed" VARCHAR(100),
  "executedBy" VARCHAR(255),
  "requiresLabels" TEXT,
  "retryAfterMs" BIGINT,
  "deadlineEpochMs" BIGINT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE("workflowRunId", "stepName")
);

CREATE TABLE IF NOT EXISTS workflow_step_logs (
  id VARCHAR(36) PRIMARY KEY,
  "stepId" VARCHAR(36) NOT NULL,
  "workflowRunId" VARCHAR(36) REFERENCES workflow_runs(id) ON DELETE CASCADE,
  "tenantId" VARCHAR(255) NOT NULL,
  event VARCHAR(30) NOT NULL,
  data TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflow_signals (
  id VARCHAR(36) PRIMARY KEY,
  "workflowRunId" VARCHAR(36) NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  "tenantId" VARCHAR(255) NOT NULL,
  "signalName" VARCHAR(255) NOT NULL,
  data TEXT NOT NULL,
  "processedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS external_actions (
  id VARCHAR(36) PRIMARY KEY,
  "workflowRunId" VARCHAR(36) NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  "stepName" VARCHAR(255) NOT NULL,
  attempt INTEGER NOT NULL,
  "tenantId" VARCHAR(255) NOT NULL,
  provider VARCHAR(100) NOT NULL,
  "actionType" VARCHAR(100) NOT NULL,
  "idempotencyKey" VARCHAR(500) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  "externalId" VARCHAR(500),
  request TEXT,
  response TEXT,
  error TEXT,
  "traceId" VARCHAR(36),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMPTZ,
  UNIQUE("tenantId", "idempotencyKey")
);

CREATE INDEX IF NOT EXISTS idx_runs_tenant_status ON workflow_runs("tenantId", status);
CREATE INDEX IF NOT EXISTS idx_steps_run_step ON workflow_steps("workflowRunId", "stepName");
CREATE INDEX IF NOT EXISTS idx_steps_tenant_status ON workflow_steps("tenantId", status);
CREATE INDEX IF NOT EXISTS idx_logs_tenant_step ON workflow_step_logs("tenantId", "stepId");
CREATE INDEX IF NOT EXISTS idx_signals_run_signal ON workflow_signals("workflowRunId", "signalName", "processedAt");
CREATE INDEX IF NOT EXISTS idx_external_actions_key ON external_actions("idempotencyKey");
CREATE INDEX IF NOT EXISTS idx_external_actions_step ON external_actions("workflowRunId", "stepName", attempt);

CREATE TABLE IF NOT EXISTS workflow_events (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  "eventType" VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  payload TEXT,
  "idempotencyKey" VARCHAR(500),
  "entityKey" VARCHAR(500),
  "sequenceNumber" INTEGER,
  "traceId" VARCHAR(36),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  error TEXT,
  "processedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE("tenantId", "idempotencyKey")
);
CREATE INDEX IF NOT EXISTS idx_events_tenant_type ON workflow_events("tenantId", "eventType", status);
CREATE INDEX IF NOT EXISTS idx_events_entity ON workflow_events("entityKey", "sequenceNumber");

CREATE TABLE IF NOT EXISTS workflow_event_subscriptions (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  "eventType" VARCHAR(255) NOT NULL,
  "workflowName" VARCHAR(255) NOT NULL,
  "filterExpression" TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_event_subs_tenant_type ON workflow_event_subscriptions("tenantId", "eventType", active);

CREATE TABLE IF NOT EXISTS worker_nodes (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255),
  "accountId" VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  hostname VARCHAR(255),
  capabilities TEXT,
  "secretHash" VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  "lastHeartbeatAt" TIMESTAMPTZ,
  "registeredAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_workers_tenant_status ON worker_nodes("tenantId", status);

CREATE TABLE IF NOT EXISTS workflow_definitions (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  version VARCHAR(50) NOT NULL,
  definition TEXT NOT NULL,
  "createdBy" VARCHAR(255),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_definitions_tenant_name ON workflow_definitions("tenantId", name);

CREATE TABLE IF NOT EXISTS workflow_tasks (
  id VARCHAR(36) PRIMARY KEY,
  "workflowRunId" VARCHAR(36) NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  "stepName" VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  payload TEXT,
  result TEXT,
  error TEXT,
  attempt INTEGER NOT NULL DEFAULT 0,
  "maxRetries" INTEGER NOT NULL DEFAULT 3,
  priority INTEGER,
  "queuePartitionKey" VARCHAR(255),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tasks_run_step ON workflow_tasks("workflowRunId", "stepName", status);
CREATE INDEX IF NOT EXISTS idx_tasks_status_priority ON workflow_tasks(status, priority DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_tasks_partition ON workflow_tasks("queuePartitionKey", status) WHERE "queuePartitionKey" IS NOT NULL;

CREATE TABLE IF NOT EXISTS workflow_schedules (
  id VARCHAR(255) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  "workflowName" VARCHAR(255) NOT NULL,
  "cronExpression" VARCHAR(100) NOT NULL,
  timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
  "runOnInit" BOOLEAN NOT NULL DEFAULT false,
  input TEXT,
  "nextRunAtEpochMs" BIGINT NOT NULL,
  "lastRunAtEpochMs" BIGINT,
  active BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_schedules_next_epoch ON workflow_schedules(active, "nextRunAtEpochMs");

CREATE TABLE IF NOT EXISTS agent_tokens (
  id VARCHAR(36) PRIMARY KEY,
  "tenantId" VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  "usedBy" VARCHAR(36),
  "expiresAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_agent_tokens_token ON agent_tokens(token);

-- DBOS-parity: missing indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_runs_trace_id ON workflow_runs("traceId");
CREATE INDEX IF NOT EXISTS idx_runs_created_at ON workflow_runs("createdAt");
CREATE INDEX IF NOT EXISTS idx_runs_tenant_name ON workflow_runs("tenantId", "workflowName");
CREATE INDEX IF NOT EXISTS idx_steps_active ON workflow_steps("workflowRunId", status)
  WHERE status IN ('PENDING', 'QUEUED', 'RUNNING', 'WAITING_HUMAN');

CREATE TABLE IF NOT EXISTS workflow_streams (
  id VARCHAR(36) PRIMARY KEY,
  "workflowRunId" VARCHAR(36) NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  key VARCHAR(255) NOT NULL,
  "offset" INTEGER NOT NULL,
  value TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_streams_run_key ON workflow_streams("workflowRunId", key, "offset");

CREATE INDEX IF NOT EXISTS idx_runs_delayed ON workflow_runs(status, "delayUntilEpochMs")
  WHERE status = 'DELAYED';

-- v0.5.0: retry backoff — column for existing tables (CREATE TABLE already includes it for new installs)
ALTER TABLE workflow_steps ADD COLUMN IF NOT EXISTS "retryAfterMs" BIGINT;

-- v0.5.0: timezone-aware scheduling + runOnInit
ALTER TABLE workflow_schedules ADD COLUMN IF NOT EXISTS timezone VARCHAR(100) NOT NULL DEFAULT 'UTC';
ALTER TABLE workflow_schedules ADD COLUMN IF NOT EXISTS "runOnInit" BOOLEAN NOT NULL DEFAULT false;

-- v0.5.0: TIMESTAMP → TIMESTAMPTZ (stores absolute instants, immune to server tz changes)
-- Postgres converts losslessly by assuming existing values are in the current server timezone.
ALTER TABLE workflow_runs ALTER COLUMN "startedAt" TYPE TIMESTAMPTZ USING "startedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_runs ALTER COLUMN "completedAt" TYPE TIMESTAMPTZ USING "completedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_runs ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_runs ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "startedAt" TYPE TIMESTAMPTZ USING "startedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "completedAt" TYPE TIMESTAMPTZ USING "completedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "scheduledAt" TYPE TIMESTAMPTZ USING "scheduledAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "lastHeartbeatAt" TYPE TIMESTAMPTZ USING "lastHeartbeatAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "humanRespondedAt" TYPE TIMESTAMPTZ USING "humanRespondedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_steps ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_step_logs ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_signals ALTER COLUMN "processedAt" TYPE TIMESTAMPTZ USING "processedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_signals ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE external_actions ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE external_actions ALTER COLUMN "completedAt" TYPE TIMESTAMPTZ USING "completedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_events ALTER COLUMN "processedAt" TYPE TIMESTAMPTZ USING "processedAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE workflow_events ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE worker_nodes ALTER COLUMN "lastHeartbeatAt" TYPE TIMESTAMPTZ USING "lastHeartbeatAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE worker_nodes ALTER COLUMN "registeredAt" TYPE TIMESTAMPTZ USING "registeredAt" AT TIME ZONE current_setting('TIMEZONE');
ALTER TABLE worker_nodes ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE current_setting('TIMEZONE');
`
